[package]
name = "nvm"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "size"
path = "exe/size.rs"
test = false

[[bin]]
name = "nvm"
path = "src/main.rs"
test = false

[[bench]]
name = "bc"
harness = false

[dev-dependencies]
criterion = "0.5.1"
pad = "0.1.6"
colored = "3.0.0"
